#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "develop/pre-push-config" ]; then
  echo "You can't push directly to master branch"
  exit 1
fi

if [ "$branch" = "main" ]; then
  echo "You can't push directly to master branch"
  exit 1
fi
